CREATE TABLE FOLLOW_UP_ITEM (
    ID VARCHAR(50) NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    SUMMARY VARCHAR(4000) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_FOLLOW_UP_ITEM PRIMARY KEY (ID),
    CONSTRAINT UK_FOLLOW_UP_ITEM_OWNER_ID UNIQUE (OWNER_ID, ID)
);
CREATE INDEX IDX_FOLLOW_UP_ITEM_OWNER_ID ON FOLLOW_UP_ITEM (OWNER_ID);

CREATE TABLE EVIDENCE_REFERENCE (
    ID VARCHAR(50) NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    SOURCE_TYPE VARCHAR(50) NOT NULL,
    SOURCE_ID VARCHAR(500) NOT NULL,
    OCCURRED_AT TIMESTAMP NOT NULL,
    AUTHOR VARCHAR(500) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    EXCERPT VARCHAR(1000) NOT NULL,
    CONFIDENCE DOUBLE PRECISION NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_EVIDENCE_REFERENCE PRIMARY KEY (ID),
    CONSTRAINT UK_EVIDENCE_REFERENCE_OWNER_SOURCE UNIQUE (OWNER_ID, SOURCE_TYPE, SOURCE_ID)
);
CREATE INDEX IDX_EVIDENCE_REFERENCE_OWNER_SOURCE ON EVIDENCE_REFERENCE (OWNER_ID, SOURCE_TYPE, SOURCE_ID);

CREATE TABLE FOLLOW_UP_EVIDENCE_REFERENCE (
    OWNER_ID VARCHAR(500) NOT NULL,
    FOLLOW_UP_ITEM_ID VARCHAR(50) NOT NULL,
    EVIDENCE_REFERENCE_ID VARCHAR(50) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_FOLLOW_UP_EVIDENCE_REFERENCE PRIMARY KEY (OWNER_ID, FOLLOW_UP_ITEM_ID, EVIDENCE_REFERENCE_ID),
    CONSTRAINT FK_FOLLOW_UP_EVIDENCE_REFERENCE_ITEM FOREIGN KEY (FOLLOW_UP_ITEM_ID) REFERENCES FOLLOW_UP_ITEM (ID),
    CONSTRAINT FK_FOLLOW_UP_EVIDENCE_REFERENCE_EVIDENCE FOREIGN KEY (EVIDENCE_REFERENCE_ID) REFERENCES EVIDENCE_REFERENCE (ID)
);
CREATE INDEX IDX_FOLLOW_UP_EVIDENCE_REFERENCE_ITEM ON FOLLOW_UP_EVIDENCE_REFERENCE (OWNER_ID, FOLLOW_UP_ITEM_ID);
CREATE INDEX IDX_FOLLOW_UP_EVIDENCE_REFERENCE_EVIDENCE ON FOLLOW_UP_EVIDENCE_REFERENCE (OWNER_ID, EVIDENCE_REFERENCE_ID);

CREATE TABLE WORK_STATUS_RECORD (
    ID VARCHAR(50) NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    FOLLOW_UP_ITEM_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    REASON VARCHAR(4000) NOT NULL,
    STATUS_SOURCE VARCHAR(50) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_WORK_STATUS_RECORD PRIMARY KEY (ID),
    CONSTRAINT FK_WORK_STATUS_RECORD_FOLLOW_UP_ITEM FOREIGN KEY (FOLLOW_UP_ITEM_ID) REFERENCES FOLLOW_UP_ITEM (ID)
);
CREATE INDEX IDX_WORK_STATUS_RECORD_OWNER_ITEM_UPDATED ON WORK_STATUS_RECORD (OWNER_ID, FOLLOW_UP_ITEM_ID, UPDATED_AT, ID);

CREATE TABLE ACTION_DRAFT (
    ID VARCHAR(50) NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    FOLLOW_UP_ITEM_ID VARCHAR(50) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    RECIPIENTS TEXT NOT NULL,
    SUBJECT VARCHAR(1000),
    BODY TEXT,
    MEETING_TITLE VARCHAR(1000),
    SELECTED_STARTS_AT TIMESTAMP,
    SELECTED_ENDS_AT TIMESTAMP,
    AGENDA TEXT NOT NULL,
    EDITABLE_CONTEXT TEXT,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_ACTION_DRAFT PRIMARY KEY (ID),
    CONSTRAINT FK_ACTION_DRAFT_FOLLOW_UP_ITEM FOREIGN KEY (FOLLOW_UP_ITEM_ID) REFERENCES FOLLOW_UP_ITEM (ID)
);
CREATE INDEX IDX_ACTION_DRAFT_OWNER_ID ON ACTION_DRAFT (OWNER_ID, ID);

CREATE TABLE ACTION_STATE (
    OWNER_ID VARCHAR(500) NOT NULL,
    DRAFT_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    APPROVED_CONTENT_REFERENCE VARCHAR(1000),
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_ACTION_STATE PRIMARY KEY (OWNER_ID, DRAFT_ID),
    CONSTRAINT FK_ACTION_STATE_DRAFT FOREIGN KEY (DRAFT_ID) REFERENCES ACTION_DRAFT (ID)
);

CREATE TABLE AUDIT_LOG_ENTRY (
    ID VARCHAR(50) NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    FOLLOW_UP_ITEM_ID VARCHAR(50) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    OCCURRED_AT TIMESTAMP NOT NULL,
    APPROVAL_STATUS VARCHAR(50) NOT NULL,
    APPROVED_CONTENT_REFERENCE VARCHAR(1000) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_AUDIT_LOG_ENTRY PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_LOG_ENTRY_FOLLOW_UP_ITEM FOREIGN KEY (FOLLOW_UP_ITEM_ID) REFERENCES FOLLOW_UP_ITEM (ID)
);
CREATE INDEX IDX_AUDIT_LOG_ENTRY_OWNER_OCCURRED ON AUDIT_LOG_ENTRY (OWNER_ID, OCCURRED_AT, ID);
