CREATE TABLE EVIDENCE_REFERENCE_VERSION (
    ID VARCHAR(50) NOT NULL,
    EVIDENCE_REFERENCE_ID VARCHAR(50) NOT NULL,
    VERSION INTEGER NOT NULL,
    OWNER_ID VARCHAR(500) NOT NULL,
    SOURCE_TYPE VARCHAR(50) NOT NULL,
    SOURCE_ID VARCHAR(500) NOT NULL,
    OCCURRED_AT TIMESTAMP NOT NULL,
    AUTHOR VARCHAR(500) NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    EXCERPT VARCHAR(1000) NOT NULL,
    CONFIDENCE DOUBLE PRECISION NOT NULL,
    RECORDED_AT TIMESTAMP NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(500) NOT NULL,
    CHANGED TIMESTAMP NOT NULL,
    CHANGED_BY VARCHAR(500) NOT NULL,
    CONSTRAINT PK_EVIDENCE_REFERENCE_VERSION PRIMARY KEY (ID),
    CONSTRAINT UK_EVIDENCE_REFERENCE_VERSION_REFERENCE_VERSION
        UNIQUE (EVIDENCE_REFERENCE_ID, VERSION),
    CONSTRAINT FK_EVIDENCE_REFERENCE_VERSION_REFERENCE
        FOREIGN KEY (EVIDENCE_REFERENCE_ID) REFERENCES EVIDENCE_REFERENCE (ID)
);

CREATE INDEX IDX_EVIDENCE_REFERENCE_VERSION_OWNER_REFERENCE
    ON EVIDENCE_REFERENCE_VERSION (OWNER_ID, EVIDENCE_REFERENCE_ID);
