name: Pull request build

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '26'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon build --warning-mode all
